[theme]
base = "dark"
primaryColor = "#E10600"
backgroundColor = "#050505"
secondaryBackgroundColor = "#111111"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false